name 'apache'
maintainer 'Erick Ramirez'
maintainer_email 'erick.ramirez@softtek.com'
license 'close'
description 'Installs/Configures apache'
long_description 'Installs/Configures apache'
version '0.2.2'
depends 'apt'
